apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: blog-boilerplate
build:
  local:
    push: false
  artifacts:
    - image: alfredoizjr/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: alfredoizjr/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: alfredoizjr/client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.tsx"
            dest: .
manifests:
  rawYaml:
    - k8s/dev/*
